#!/usr/bin/env bash
# Regenerates k5.sm_80.ptx (PLAN.md §3 fixture policy). Rerunning on the
# same toolchain is a no-op diff modulo the date line, so a regen diff is
# information: it means the source or the toolchain changed.
set -euo pipefail
cd "$(dirname "$0")"
repo=$(git rev-parse --show-toplevel)
src=test/5_2d_blocktiling.cuh
flags="-ptx -lineinfo -frandom-seed=k5 -arch=sm_80"
out=k5.sm_80.ptx
nvcc $flags -I"$repo/test" -o "$out.body" k5.cu
{
    echo "//"
    echo "// Provenance: generated by regen.sh in this directory — do not edit."
    echo "//   source:   $src @ $(git -C "$repo" log -n1 --format=%h -- "$src")"
    echo "//   wrapper:  k5.cu"
    echo "//   compiler: $(nvcc --version | grep release)"
    echo "//   flags:    $flags"
    echo "//   date:     $(date -u +%Y-%m-%d)"
    echo "//"
    cat "$out.body"
} > "$out"
rm "$out.body"
